package Calculator;


/**
* Calculator/_AddImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from add.idl
* Tuesday, February 16, 2016 12:07:25 PM UTC
*/

public abstract class _AddImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Calculator.Add, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AddImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculator/Add/add
       {
         int num1 = in.read_long ();
         int num2 = in.read_long ();
         int $result = (int)0;
         $result = this.add (num1, num2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculator/Add:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AddImplBase
