package Calculator;


/**
* Calculator/Add.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from add.idl
* Tuesday, February 16, 2016 12:07:25 PM UTC
*/

public interface Add extends AddOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Add
