package Calculator;


/**
* Calculator/AddHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from add.idl
* Tuesday, February 16, 2016 12:07:25 PM UTC
*/

abstract public class AddHelper
{
  private static String  _id = "IDL:Calculator/Add:1.0";

  public static void insert (org.omg.CORBA.Any a, Calculator.Add that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Calculator.Add extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Calculator.AddHelper.id (), "Add");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Calculator.Add read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AddStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Calculator.Add value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Calculator.Add narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculator.Add)
      return (Calculator.Add)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculator._AddStub stub = new Calculator._AddStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Calculator.Add unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculator.Add)
      return (Calculator.Add)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculator._AddStub stub = new Calculator._AddStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
