package Calculator;


/**
* Calculator/AddOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from add.idl
* Tuesday, February 16, 2016 12:07:25 PM UTC
*/

public interface AddOperations 
{
  int add (int num1, int num2);
} // interface AddOperations
